server:
  port: 8809

repeatSubmit:
  intervalTime: 15
token:
  header: REPEAT-SUBMIT-HEADER
spring:
  application:
    name: REPEAT-SUBMIT-REDIS-DEMO

  redis:
    timeout: 50000
    database: 0
    password: eric1988
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
    sentinel:
      master: mymaster
      nodes: 10.1.164.192:5008,10.1.164.192:5009,10.1.164.192:5010
  server:
    port: 8088